### ISSUE TITLE
Contribute to your open source project PhreshPlayer

### ISSUE THREAD

**Issue by nunojesus** [Phreshhh/PhreshPlayer#1]
Hello, my name is Nuno Jesus and I am a web designer, I am currently looking for opensource projects to make my contribution, I would like to know if there is any work for me to do, within my professional area. If you want I can make you a new logotype, or banners, or other type of graphic design work.
Greetings

**Comment by Phreshhh** [comment]
Hi!

Thanks for your offer. This project is waiting for major upgrade in electron/chromium, but if you want, you can help me in my projects in the future. My next project will be a cross-platform file sync app. But first, can you show me some reference work? (here or in email) Thanks.

Have a nice day!

**Comment by doblehachege** [comment]
Greetings Sr. Kis, I'm not sure if you had the chance to check a logo design I proposed as contribution  for your Phresh Player project, I'd like to take advantage of this conversation to show it, just in case, I hope you can take a look at the whole project here: https://utopian.io/utopian-io/@callmeh/logo-proposal-for-phresh-player and tell me your opinions about it and if you already watched it there's no problema t all.

![phresh-player-horizontal-1](https://user-images.githubusercontent.com/36449779/38258606-f4a585a2-3730-11e8-8685-e3bbec0ee46f.png)

**Comment by Phreshhh** [comment]
Dear Hernández!

Sorry about my mistake.

The tools first two points.. lol

Its really nice job, I like it, thanks. The filled logo is nice also, but the gap styled is the bullseye. Love it.
I accept with thanks your contribution. Please write the further action's steps for the joint work. (This is my first situation as such)

Have a nice day!

Thanks, Phresh
