### ISSUE TITLE
doesn't read ac-3 audio codec in videos

### ISSUE THREAD

**Issue by ghost** [Phreshhh/PhreshPlayer#4]
doesn't read the audio codec above, please offer suport for this type of file. thx great work.

**Comment by Phreshhh** [comment]
Dear @Lucas-bash !

You can find in the readme the supported file types:

mp4 **(aac audio only. ac3 not, but you can convert to aac)**
webm
mkv **(aac audio only. ac3 not, but you can convert to aac)**
m4v
ogg (ogv)
mov
mp3
flac

This is the default and only one web mediaplayer (i havent influence on the development). Currently not support the ac3 audio tracks, but i built into the app an converter.  Recently i moved this feature into a plugin: [ffmpeg-video-converter](https://github.com/Phreshhh/PhreshPlayer-plugins/tree/master/ffmpeg-video-converter)

This converter plugin can convert also the ac3 to aac, not just the video container types.
You can install the [plugins](https://github.com/Phreshhh/PhreshPlayer-plugins) with ease from the app [v1.1.3](https://github.com/Phreshhh/PhreshPlayer/releases/tag/v1.1.3).

Best regards..

**Comment by ghost** [comment]
Thanks for the answer, I've been used moonplayer an awesome video player in
appimage that runs everything you should take a look on it, it might be
very useful for you.

Em quarta-feira, 2 de outubro de 2019, Kis Krisztián <
notifications@github.com> escreveu:

**Comment by Phreshhh** [comment]
Yes i know it. :) - and i tired. Also good player.

The moonplayer is written in another programming language (C++ and a bit Python) and based on an existing player (mpv) core code (and codec-pack). I based my player from mpv too, but only the design & UI, not the code.

Unfortunately not too useful for my project, but maybe in the future, i'll can add some extra feature for my player with Python.

Thanks for the idea.

**Comment by ghost** [comment]
have you though about make some kind of pdf reader in appimage? doesn't
seems to me exist some pdf reader in appimage?

Em sex, 4 de out de 2019 às 12:28, Kis Krisztián <notifications@github.com>
escreveu:

**Comment by Phreshhh** [comment]
I dont think about document reader / organizer. Exist some good in the place..
(I think about, media maker & organizer. video, audio record, and organize. Can use memory bank example.. video diary or simple organize, your series, films, self maked curses, etc)

But..
This reader is packable to appimage and .deb too with a bit code & package.json extend:
[lector](https://github.com/sagargurtu/lector)
or
This is an multi document reader and organizer, i like it. This can read .pdf too and have .deb & .appimage pack also: [polar-bookshelf](https://github.com/burtonator/polar-bookshelf)
