### ISSUE TITLE
What about Soda Player

### ISSUE THREAD

**Issue by talks2much** [Phreshhh/PhreshPlayer#7]
We have [Soda Player](https://www.sodaplayer.com/), which is the best player in the world, isn't it?

Unfortunately it doesn't maintained anymore and has lack of features, but I don't know any alternatives to Soda :(

Would like to hear thoughts on it

**Comment by abdulmoizhussain** [comment]
https://www.reddit.com/r/Piracy/comments/8q2pg3/anyone_who_can_explain_why_soda_player_is/

May be, this can be your reason to leave Soda :P

If you are looking for Ace Stream, there are loads of alternatives which you can have like, Media player classic, GOM player etc.

**Comment by talks2much** [comment]
I've deobfuscated it's code a long time ago and I'm pretty sure that it didn't steal anything. When I initially created the issue I didn't know about Stremio which works significantly better than any other torrent streaming client (this is the best client I have seen so far), and also builtin open subtitles integration is just insane.

But, Soda Player has the best possible UI with the best possible color palette, I really don't understand why every player can't have so beautiful slider, smooth animations with simple and friendly UX.

**Comment by Phreshhh** [comment]
I like the soda ui and colors. Really pretty interface. I will make some change in the phreshplayer ui with this style when i'll have time for that. Now higher prio the plugin system review and some useful plugin.
